# TO RUN COMMAND
#             : docker-compose up -d
version: "3.7"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: 'password'

  rabbitmq:
     image: rabbitmq:3-management
     container_name: rabbitmq
     ports:
        - 15671:15671
        - 15672:15672
        - 15691:15691
        - 15692:15692
        - 25672:25672
        - 4369:4369
        - 5671:5671
        - 5672:5672
           
  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - 7000:7000
        - 7001:7001
        - 7199:7199
        - 9042:9042
        - 9160:9160
         
